pythonProject/app_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

# URLの全体設計
urlpatterns = [
    # 今回作成するアプリ「app_folder」にアクセスするURL
    path('app_folder/', include('app_folder.urls')),
    # 何もURLを指定しない場合（app_config/views.pyで、自動的に「app_folder」にアクセスするよう設定済み）
    path('', views.index, name='index'),
    # 管理サイトにアクセスするURL
    path('admin/', admin.site.urls),
]

# メディアファイル公開用のURL設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    path('top_page/', views.top_page, name='top_page'),
    path('post_page/', views.post_page, name='post_page'),
    path('bat_post_page/', views.bat_post_page, name='bat_post_page'),
    path('return_top_page/', views.return_top_page, name='return_top_page'),
    path('good_return_page/', views.good_return_page, name='good_return_page'),
    path('next_choice_page/', views.next_choice_page, name='next_choice_page'),
    path('bat_return_page/', views.bat_return_page, name='bat_return_page'),
]

pythonProject/app_folder/models.py
from django.db import models


class strDB(models.Model):
    class Meta:
        db_table = 'str_table'
        verbose_name_plural = 'str_table'

    str_id = models.IntegerField('id', null=True, blank=True, )
    str = models.CharField('str', max_length=100, null=True, blank=True, )


class GoodReturnDB(models.Model):
    class Meta:
        db_table = 'good_return_table'
        verbose_name_plural = 'good_return_table'

    good_id = models.IntegerField('id', null=True, blank=True, )
    good_return_str = models.CharField('good_return_str', max_length=100, null=True, blank=True, )


class BatReturnDB(models.Model):
    class Meta:
        db_table = 'bat_return_table'
        verbose_name_plural = 'bat_return_table'

    bat_id = models.IntegerField('id', null=True, blank=True, )
    bat_return_str = models.CharField('bat_return_str', max_length=100, null=True, blank=True, )

pythonProject/app_config/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View


class index(View):
    def get(self, request, *args, **kwargs):
        return redirect(reverse('app_folder:top_page'))


index = index.as_view()

pythonProject/app_folder/views.py
import random

from django.shortcuts import render
from django.views import View
from .models import GoodReturnDB, strDB
from .models import BatReturnDB


class TopView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'app_folder/top.html')

    def post(self, request, *args, **kwargs):
        # メッセージ格納
        result = strDB.objects.filter(id=3)
        result_choice = result[0].str
        context = {'result_choice': result_choice}

        return render(request, 'app_folder/choice.html', context=context, )


top_page = TopView.as_view()


class PostView(View):
    def get(self, request, *args, **kwargs):
        result = strDB.objects.filter(id=1)
        result_str = result[0].str
        context = {'result_str': result_str}
        # セッションに保存する
        request.session['thing'] = "good_thing"

        return render(request, 'app_folder/form.html', context=context, )


post_page = PostView.as_view()


class BatPostView(View):
    def get(self, request, *args, **kwargs):
        result = strDB.objects.filter(id=2)
        result_str = result[0].str
        context = {'result_str': result_str}
        # セッションに保存する
        request.session['thing'] = "bat_thing"
        return render(request, 'app_folder/form.html', context=context, )


bat_post_page = BatPostView.as_view()


class ToTopView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'app_folder/to_top.html')

    def post(self, request, *args, **kwargs):
        return render(request, 'app_folder/top.html')


return_top_page = ToTopView.as_view()


class GoodReturnView(View):
    def get(self, request, *args, **kwargs):
        i = random.randint(1, 6)
        result = GoodReturnDB.objects.filter(id=i)
        result_return = result[0].good_return_str
        context = {'result_return': result_return}
        return render(request, 'app_folder/return.html', context=context, )


good_return_page = GoodReturnView.as_view()


class NextChoiceView(View):
    def get(self, request, *args, **kwargs):
        # セッションから選択ボタン情報削除
        del request.session['thing']
        # メッセージ格納
        result = strDB.objects.filter(id=4)
        result_choice = result[0].str
        context = {'result_choice': result_choice}

        return render(request, 'app_folder/choice.html', context=context, )


next_choice_page = NextChoiceView.as_view()


class BatReturnView(View):
    def get(self, request, *args, **kwargs):
        i = random.randint(1, 6)
        result = BatReturnDB.objects.filter(id=i)
        result_return = result[0].bat_return_str
        context = {'result_return': result_return}
        return render(request, 'app_folder/return.html', context=context, )


bat_return_page = BatReturnView.as_view()

pythonProject/templates/app_folder/choice.html
{% extends 'base.html' %}
{% block contents %}

<!-- <h4 class="mt-5 mb-4 border-bottom"></h4> -->
<div class="container-fluid">
  <div class="row">
    <div class="col-4">
        <div class="arrow_box">
            <p><span class="test">{{result_choice}}</span></p>
        </div>
    </div>
  </div>
    <form  action="{% url 'app_folder:post_page' %}" method="get">
        <div class="text-align : center">
          <button type="submit" name="button" class="btn btn-info">
            よかったことについて
          </button>
        </div>
        {% csrf_token %}
    </form>
    <form  action="{% url 'app_folder:bat_post_page' %}" method="get">
        <div class="text-align : center">
          <button type="submit" name="button" class="btn btn-info">
            ぐち、なやみについて
          </button>
        </div>
         {% csrf_token %}
    </form>
    <form  action="{% url 'app_folder:return_top_page' %}" method="get">
        <div class="text-align : center">
          <button type="submit" name="button" class="btn btn-info">
            なにもない
          </button>
        </div>
        {% csrf_token %}
    </form>
</div>

{% endblock %}

pythonProject/templates/app_folder/form.html
{% extends 'base.html' %}
{% block contents %}

<div class="container-fluid">
    <div class="row">
        <div class="col-4">
            <div class="arrow_box">

                <p><span class="test">{{result_str}}</span></p>
            </div>
        </div>
    </div>
    <div class="text-align : center">
          <textarea name="text" class="btn btn-info" maxlength="500" style="width:400px; height:100px;" cols="40"
                    rows="8">
          </textarea>
    </div>
    {% if request.session.thing == 'good_thing' %}
    <form action="{% url 'app_folder:good_return_page' %}" method="get">
        {% elif request.session.thing == 'bat_thing' %}
        <form action="{% url 'app_folder:bat_return_page' %}" method="get">
            {% endif %}
            <div class="text-align : center">
                <button type="submit" name="button" class="btn btn-info">
                    OK
                </button>
            </div>
            {% csrf_token %}
        </form>
</div>

{% endblock %}

pythonProject/templates/app_folder/return.html
{% extends 'base.html' %}
{% block contents %}

<div class="container-fluid">
  <div class="row">
    <div class="col-4">
        <div class="arrow_box">
            <p><span class="test">{{result_return}}</span></p></p>
        </div>
    </div>
  </div>
    <form  action="{% url 'app_folder:next_choice_page' %}" method="get">
        <div class="text-align : center">
          <button type="submit" name="button" class="btn btn-info">
            OK
          </button>
        </div>
        {% csrf_token %}
    </form>
</div>

{% endblock %}

pythonProject/templates/app_folder/to_top.html
{% extends 'base.html' %}
{% block contents %}

<div class="container-fluid">
  <div class="row">
    <div class="col-4">
        <div class="arrow_box">
            <p><span class="test">何もないのはいい便りだ。またなにかあったら教えてね～</span></p>
        </div>
    </div>
  </div>
    <form  action="{% url 'app_folder:return_top_page' %}" method="post">
        <div class="text-align : center">
          <button type="submit" name="button" class="btn btn-info">
            TOP
          </button>
        </div>
        {% csrf_token %}
    </form>
</div>

{% endblock %}

pythonProject/templates/app_folder/top.html
{% extends 'base.html' %}
{% block contents %}

<form  action="{% url 'app_folder:top_page' %}" method="post">
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
      <div class="text-left align-bottom">
          <button type="submit" name="button" class="btn btn-info">
            はなす
          </button>
      </div>
    </div>
    </div>
  </div>
</div>
{% csrf_token %}
</form>

{% endblock %}

pythonProject/templates/app_folder/top_page.html
{% extends 'base.html' %}
{% block contents %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5 border-bottom">
    <h1 class="h2">トップページ</h1>
</div>

<div>
    <h4>ここにコンテンツを記述する</h4>
</div>

{% endblock %}

pythonProject/templates/base.html
<!DOCTYPE html>

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type='text/css' href="{% static 'css/new.css'%}">
    <link rel="stylesheet" href="https://cccabinet.jpn.org/bootstrap4/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="../../static/js/jquery.textillate.js"></script>
    <script src="../../static/js/jquery.lettering.js"></script>

    <script>
$(function () {
    $('.test').textillate({
      loop: false,
      minDisplayTime: 1000,
      initialDelay: 0,
      autoStart: true,

      in: {
        effect: 'bounceIn',
        delayScale: 1.5,
        delay: 50,
        sync: false,
        shuffle: false
      },

      out: {
        effect: 'pulse',
        delayScale: 1.5,
        delay: 50,
        sync: false,
        shuffle: false
      }
    });
   $('#hoge').textillate({
      loop: true,
      minDisplayTime: 3000,
      initialDelay: 2000,
      autoStart: true,

      in: {
        effect: 'fadeIn',
        delayScale: 1.5,
        delay: 20,
        sync: false,
        shuffle: false
      },

      out: {
        effect: 'fadeOut',
        delayScale: 1.5,
        delay: 50,
        sync: false,
        shuffle: false
      }
    });
})
    </script>

    <title> なまけもの </title>

    {% block extra_css %}{% endblock %}

</head>

<body>
<!-- ↓↓１番上 ナビゲーションバー↓↓ -->

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg fixed-top navbar-dark bs-navbar" style='background-color:darkgreen;'
                 id="bs-navbar">
                <a class="navbar-brand mr-md-2" href="/app_folder/top_page">
                    なまけもののもり
                </a>
                <!-- ↓↓レイアウト調整ダミー↓↓ -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="#"> </a></li>
                    <li class="nav-item"><a class="nav-link" href="#"> </a></li>
                </ul>
                <!-- ↑↑ダミー↑↑ -->
            </nav>
        </div>
    </div>
</div>

<!-- 「サイドバー」 「コンテンツ本体部分」 -->

<div id="content" class="container-fluid">
    <div class="row flex-xl-nowrap">

        <div id="sidemenu" class="col-2 d-none d-md-block bg-light sidebar align-self-start">

        </div id="sidemenu">

        <!-- ↑↑サイドバー↑↑ -->

        <!-- ↓↓コンテンツ本体↓↓ -->
        <br>
        {% load static %} <img src="{% static 'images/sloth.png' %}" alt="Hi!"/>
        <br/>

        <div class="col-10">
            {% block contents %}
            {% endblock %}
        </div>
        <!-- ↑↑コンテンツ本体↑↑ -->
    </div>
</div>
</div>
</body>
</html>

<!-- サイドバー使用アイコン -->
<!-- 使用できるアイコン一覧： https://voyager-jp.com/blog/javascript/feather/ -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script>feather.replace()</script>
</div>